steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud auth print-access-token > /workspace/gcp_token

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        DOCKER_BUILDKIT=1 docker build \
          --secret id=GCP_TOKEN,src=/workspace/gcp_token \
          -t asia-south1-docker.pkg.dev/project-a4281931-0724-4c2c-b3a/backend-service/backend-service-staging:$COMMIT_SHA \
          .
        rm -f /workspace/gcp_token

images:
  - asia-south1-docker.pkg.dev/project-a4281931-0724-4c2c-b3a/backend-service/backend-service-staging:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
