steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    secretEnv: ['GITHUB_TOKEN']
    args:
      - -c
      - |
        echo -n "$$GITHUB_TOKEN" > /tmp/github_token
        DOCKER_BUILDKIT=1 docker build \
          --secret id=github_token,src=/tmp/github_token \
          -t asia-south1-docker.pkg.dev/project-a4281931-0724-4c2c-b3a/backend-service/backend-service-staging:$COMMIT_SHA \
          .
        rm -f /tmp/github_token

images:
  - asia-south1-docker.pkg.dev/project-a4281931-0724-4c2c-b3a/backend-service/backend-service-staging:$COMMIT_SHA

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

options:
  logging: CLOUD_LOGGING_ONLY
